// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Se1myrWK9P41kQpw55ByXiQydaJnTag',
    appId: '1:820923771474:web:ba2af8d5b0cd100232cd8b',
    messagingSenderId: '820923771474',
    projectId: 'widgetspractice',
    authDomain: 'widgetspractice.firebaseapp.com',
    storageBucket: 'widgetspractice.appspot.com',
    measurementId: 'G-8WRZZQ6FZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIED5MiAWSzS8PcZnD9icYAyJGhhNLI8',
    appId: '1:820923771474:android:b6858129d8fd271a32cd8b',
    messagingSenderId: '820923771474',
    projectId: 'widgetspractice',
    storageBucket: 'widgetspractice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ19yu6oBOU0tyxJHPRKJVNcAE_Ss6qTs',
    appId: '1:820923771474:ios:62b8db7000f5bd9f32cd8b',
    messagingSenderId: '820923771474',
    projectId: 'widgetspractice',
    storageBucket: 'widgetspractice.appspot.com',
    iosBundleId: 'com.example.practice2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ19yu6oBOU0tyxJHPRKJVNcAE_Ss6qTs',
    appId: '1:820923771474:ios:62b8db7000f5bd9f32cd8b',
    messagingSenderId: '820923771474',
    projectId: 'widgetspractice',
    storageBucket: 'widgetspractice.appspot.com',
    iosBundleId: 'com.example.practice2',
  );
}
